# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1099763ceb6c788399d338bfd55734c2681eca8d2fb5e553ece0924eabd77ebee6ed0ad3ab95b93442324620abb3ae000750a876ae2c4fe5271ee788e95463e2

test:
  secret_key_base: add52d9990ae4a6f019519962f04169e7d7977b52e6277590d654057407732d54e9944b1026e86d3d5cd41d943b716bdfaa428fef413c4473e61d88b49fa3913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
